### ISSUE TITLE
Test 806 autoskips:        pal_pcie_get_legacy_irq_map unimplemented. Skipping test

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#208]
In my runs test 806 automatically skips:

```
 806 : Legacy int must be SPI & lvl-sensitive         START

       BDF - 0x400
       pal_pcie_get_legacy_irq_map unimplemented. Skipping test
       PCI_LI_01, PCI_LI_03
       Checkpoint --  2                           : Result:  SKIPPED
         END
```

Is this test some kind of work in progress?

If it skips due to lack of legacy interrupts in the system then maybe other message should be presented?

**Comment by gowthamsiddarthd** [comment]
Hi @hrw,

The API `pal_pcie_get_legacy_irq_map()` is platform-specific, and in order to execute tests related to legacy interrupts, it is essential for users to populate this API with the system's legacy IRQ map. This requirement is documented in the ReadMe for clarity, as detailed here: [GitHub ReadMe](https://github.com/ARM-software/bsa-acs#limitations).

To provide even more clarity on this matter, we have improved the print messages within the codebase, which have been incorporated into this pull request: [GitHub Pull Request](https://github.com/ARM-software/bsa-acs/pull/221).

This enhancement aims to make it crystal clear for users that they need to take this specific action to ensure the correct functioning of legacy interrupt-related tests.

Regards,
The ACS team

**Comment by hrw** [comment]
Thank you!
