### ISSUE TITLE
Is B_MEM_02 required or not?

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#233]
As I noticed that we got quite close with SBSA Reference Platform to SBSA level 3 requirements I started checking closer required BSA/SBSA checklists. And noticed some weird thing for SystemReady SR column.

docs/arm_bsa_testcase_checklist.rst says that B_MEM_02 is not required while BSA 1.0C and SBSA 7.1H specs list it as required.

Which one is proper one?

**Comment by chetan-rathore** [comment]
Hello @hrw,

Both are proper :)

The specification checklist covers all the rules that are needed for the system to be compliant with for BSA/SBSA particular level.
But some rules due to some dependencies are not feasible to test in a generic way on a given platform, so testcase_checklist captures for which bands/runtime environment the test is enabled.

Thanks,
ACS team

**Comment by hrw** [comment]
thanks
