### ISSUE TITLE
Add test for B_PE_14 (SVE implementation)?

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#238]
B_PE_14 is "SVE is optional".

Can it be implemented to PASS if SVE/SVE2 is present and SKIP otherwise?

**Comment by chetan-rathore** [comment]
Hi @hrw,

No test is present for the rule since when SVE is implemented, the rule recommends that "If implemented, Arm strongly recommends that the performance of well-optimized SVE or SVE2 code is no worse than code which uses the equivalent NEON instructions"
Currently, there is no feasible manner in which a performance comparison of the "SVE vs NEON" code can be done from ACS.

Thanks,
ACS team

**Comment by hrw** [comment]
thanks
