### ISSUE TITLE
Tests 862/863 need formatting fixes

### ISSUE THREAD

**Issue by hrw** [ARM-software/bsa-acs#364]
Tags should be on separate line.

```
[   47.552965]  862 : No extra address translation          PCI_MM_05, PCI_MM_06, PCI_MM_07
                      Checkpoint --  2                           : Result:  SKIPPED
[   47.558200]  863 : PCI legacy intr SPI ID unique         
                      Unable to fetch _PRT ACPI handle
                      Interrupt hard-wire error
                      Interrupt hard-wire errorPCI_LI_02
                      Checkpoint --  2                           : Result:  SKIPPED
```

**Comment by Sujana-M** [comment]
Hi @hrw,

The prints are from a common VAL API val_report_status at https://github.com/ARM-software/bsa-acs/blob/main/val/common/src/acs_status.c#L65 which is used by all the tests. Please find the logs at our platform for the same. 
 
[   94.719950]  862 : No extra address translation
[   94.719950]        PCI_MM_05, PCI_MM_06, PCI_MM_07
[   94.719950]        Checkpoint –  2                           : Result:  SKIPPED
 
The issue in print format may be due to platform used. 

Thanks,
ACS Team
